"""Fix Task created last edited by

Revision ID: 574d86030f04
Revises: dd17a4f26e11
Create Date: 2026-02-20 15:43:31.868358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574d86030f04'
down_revision = 'dd17a4f26e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edited_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_edited_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('last_edited_at')
        batch_op.drop_column('last_edited_by')

    # ### end Alembic commands ###
